### ISSUE TITLE
Ability to create Bucket 

### ISSUE THREAD

**Issue by exa-eswar** [exasol/bucketfs-python#53] opened 2023-02-03 13:19 UTC
In order to be able to integrate Exasol closely with ML pipelines, this feature would be highly helpful.

**Comment by Nicoretti** [comment] 2023-03-07 15:41
@exa-eswar  isn't this more or less a duplicate of #18?

**Comment by exa-eswar** [comment] 2023-03-07 16:47
@Nicoretti you are right. This is also addressing the same feature, which is ability to create Bucket via bucketfs-utils-python.

**Comment by Nicoretti** [comment] 2023-03-08 07:12
Duplicate, see #18

**Closed by Nicoretti** 2023-03-08 07:12 UTC
